title: "Joren â€” The JZone"
description: "learn something. smile a little."

# IMPORTANT for a project site
url: "https://jorenbaden-prog.github.io"
baseurl: "/The-JZone"

theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown

# Projects collection (for /projects/)
collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
