title: "Joren â€” The JZone"
description: "learn something. smile a little."

logo: "/assets/css/assets/img/logo.png"

# Project site configuration
url: "https://jorenbaden-prog.github.io"
baseurl: "/The-JZone"

theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true

author:
  name: "Joren Badendick"
  home: "/about/"
  avatar: "/assets/css/assets/img/joren-about.jpg"
  bio: "Business student at Trinity Bible College. Lover of music, cars, and serving others."
  location: "Ellendale, ND"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jorenbadendick@trinitybiblecollege.edu"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/joren.badendick"
